/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as gsn from "./GSN";
export type { gsn };
import type * as access from "./access";
export type { access };
import type * as ownership from "./ownership";
export type { ownership };
import type * as token from "./token";
export type { token };
