/**
 * Orvium API
 *  This is the OpenAPI 3.0 specification for the Orvium REST API.  Some useful links:  - [Orvium website](https://orvium.io) 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AppNotificationDTO { 
    /**
     * Notification ID
     */
    _id: string;
    /**
     * User ID
     */
    userId: string;
    /**
     * Notification title
     */
    title: string;
    /**
     * Notification content
     */
    body: string;
    /**
     * Icon to show with the notification
     */
    icon: string;
    /**
     * Mark the date where the notification was created
     */
    createdOn: Date;
    /**
     * Check if the user have read the notification
     */
    isRead: boolean;
    /**
     * Notification actions
     */
    action?: string;
}

