/**
 * Orvium API
 *  This is the OpenAPI 3.0 specification for the Orvium REST API.  Some useful links:  - [Orvium website](https://orvium.io) 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreditType } from './creditType';


export interface AuthorUpdateDTO { 
    credit: Array<CreditType>;
    /**
     * Author first name
     */
    firstName: string;
    /**
     * Author email
     */
    email?: string;
    /**
     * Author last name
     */
    lastName: string;
    /**
     * Author nickname
     */
    nickname?: string;
    /**
     * Author orcid
     */
    orcid?: string;
    /**
     * Author gravatar md5 hash
     */
    gravatar?: string;
    /**
     * The url of the image put in the profile avatar
     */
    avatar?: string;
    /**
     * Institutions of the author
     */
    institutions: Array<string>;
}

