/**
 * Orvium API
 *  This is the OpenAPI 3.0 specification for the Orvium REST API.  Some useful links:  - [Orvium website](https://orvium.io) 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BibtexReferencesYear } from './bibtexReferencesYear';
import { BibtexReferencesNumber } from './bibtexReferencesNumber';


export interface BibtexReferences { 
    year?: BibtexReferencesYear;
    number?: BibtexReferencesNumber;
    /**
     * ID to reference
     */
    id: string;
    /**
     * Reference type example: article
     */
    type: string;
    /**
     * The raw format of the bibtex citation example: @article{knuth:1984, ...
     */
    raw: string;
    /**
     * Reference title example: The independence of the continuum hypothesis
     */
    title: string;
    /**
     * The names and surnames of the current reference authors example: Lisa A. Urry and Michael L. Cain and Steven A. Wasserman and Peter V. Minorsky and Jane B. Reece
     */
    author?: string;
    /**
     * Names and surnames of the editors example: Hawley, Teresa S. and Hawley, Robert G.
     */
    editor?: string;
    /**
     * The title of the inbook refered in the publication example: Campbell Biology
     */
    booktitle?: string;
    /**
     * The url of the reference example: https://www.example.com/
     */
    publisher?: string;
    /**
     * The name of the university or degree awarding institution where the thesis was written example: Massachusetts Institute of Technology
     */
    school?: string;
    /**
     * The address of the publisher or the institution example: New York, NY
     */
    address?: string;
    /**
     * The month of the reference example: jul
     */
    month?: string;
    /**
     * The pages of that appear the reference in an article... example: 1143--1148
     */
    pages?: string;
    /**
     * The name of the journal example: Proceedings of the National Academy of Sciences
     */
    journal?: string;
    /**
     * The volume of the article... that appear the reference example: 10867
     */
    volume?: string;
    /**
     * The name of the series or set of books example: NordiCHI
     */
    series?: string;
    /**
     * The doi of the reference example: \"https://doi.org/10.0000/0000\"
     */
    doi?: string;
    /**
     * Eight-digit serial number used to uniquely identify a serial publication, such as a magazine example: 2049-3630
     */
    issn?: string;
    /**
     * The url of the reference example: https://www.example.com/
     */
    url?: string;
    /**
     * The url of the reference example: https://www.example.com/
     */
    urldate?: string;
    /**
     * The language of the reference example: English
     */
    language?: string;
    /**
     * Copyright type of the reference example: All rights reserved
     */
    copyright?: string;
    /**
     * Any information that might be interesting to the reader and did not fit into any of the other fields example: Accessed: 2018-12-06
     */
    note?: string;
    /**
     * Keywords used for searching or possibly for annotation. example: AI
     */
    keyword?: string;
    /**
     * An abstract of the work. example: An Analysis of Yukon Delta Salmon Management Rita Asgeirsson, Western Washington University
     */
    abstract?: string;
}

