/**
 * Orvium API
 *  This is the OpenAPI 3.0 specification for the Orvium REST API.  Some useful links:  - [Orvium website](https://orvium.io) 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BlockchainNetworkDTO { 
    /**
     * Blockchain codename
     */
    name: string;
    /**
     * Blockchain display name
     */
    displayName: string;
    /**
     * Blockchain Network ID
     */
    networkId: number;
    /**
     * SmartContract address of the application
     */
    appAddress: string;
    /**
     * SmartContract address of the escrow
     */
    escrowAddress: string;
    /**
     * SmartContract address of the token
     */
    tokenAddress: string;
    /**
     * URL of the blockchain explorer.
     */
    explorerUrl: string;
}

