/**
 * Orvium API
 *  This is the OpenAPI 3.0 specification for the Orvium REST API.  Some useful links:  - [Orvium website](https://orvium.io) 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CallType } from './callType';


export interface CallUpdateDTO { 
    callType?: CallType;
    /**
     * Call Title
     */
    title?: string;
    /**
     * Call Deadline
     */
    deadline?: Date;
    /**
     * Call Description
     */
    description?: string;
    /**
     * Area or subjects relevant to the call for papers/abstract
     */
    scope?: string;
    /**
     * Call Guest editors
     */
    guestEditors?: string;
    /**
     * Disciplines related to the topic of the call
     */
    disciplines?: Array<string>;
    /**
     * Call contact information
     */
    contact?: string;
    /**
     * Contact email for this call
     */
    contactEmail?: string;
    /**
     * Visibility of this call in the platform
     */
    visible?: boolean;
}



