/**
 * Orvium API
 *  This is the OpenAPI 3.0 specification for the Orvium REST API.  Some useful links:  - [Orvium website](https://orvium.io) 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommentTags } from './commentTags';
import { UserSummaryDTO } from './userSummaryDTO';


export interface CommentDTO { 
    tags: Array<CommentTags>;
    /**
     * Comment ID
     */
    _id: string;
    /**
     * Comment author user ID
     */
    user_id: string;
    /**
     * Comment community ID
     */
    community: string;
    user: UserSummaryDTO;
    /**
     * Place where the comment was created
     */
    resource: string;
    /**
     * Message of the comment
     */
    content: string;
    /**
     * Comment id of the previous comment of the conversation
     */
    parent?: string;
    /**
     * Mark if the comment has any reply
     */
    hasReplies: boolean;
    /**
     * Comment creation date
     */
    createdAt: Date;
    /**
     * Comment actions
     */
    actions: Array<string>;
}

