/**
 * Orvium API
 *  This is the OpenAPI 3.0 specification for the Orvium REST API.  Some useful links:  - [Orvium website](https://orvium.io) 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommunityType } from './communityType';
import { CalendarUpdateDTO } from './calendarUpdateDTO';
import { FileExtensions } from './fileExtensions';
import { DataCiteDTO } from './dataCiteDTO';
import { CrossrefDTO } from './crossrefDTO';
import { AccessRight } from './accessRight';
import { Track } from './track';


export interface CommunityUpdateDto { 
    type?: CommunityType;
    customLicenses?: Array<AccessRight>;
    preferredFileExtensions?: Array<FileExtensions>;
    /**
     * Community name
     */
    name?: string;
    /**
     * Community description
     */
    description?: string;
    /**
     * the country of the community
     */
    country?: string;
    /**
     * Community acknowledgement
     */
    acknowledgement?: string;
    /**
     * the twitter URL of the community
     */
    twitterURL?: string;
    /**
     * the facebook URL of the community
     */
    facebookURL?: string;
    /**
     * the website URL of the community
     */
    websiteURL?: string;
    /**
     * the guideline URL of the community
     */
    guidelinesURL?: string;
    /**
     * Community iThenticateAPI key
     */
    iThenticateAPIKey?: string;
    /**
     * Community iThenticateAPI version
     */
    iThenticateEULAVersion?: string;
    /**
     * Community issn
     */
    issn?: string;
    /**
     * Community calendar dates
     */
    calendarDates?: Array<CalendarUpdateDTO>;
    /**
     * Community calendar visible
     */
    calendarVisible?: boolean;
    /**
     * Community option to give permission to authors to invite reviewers
     */
    canAuthorInviteReviewers?: boolean;
    /**
     * Community products visible
     */
    productsVisible?: boolean;
    crossref?: CrossrefDTO | null;
    datacite?: DataCiteDTO | null;
    /**
     * New community tracks
     */
    newTracks?: Array<Track>;
    /**
     * The identity of the reviewer is shown to the author of the publication
     */
    showIdentityToAuthor?: boolean;
    /**
     * The identity of the reviewer is shown to everyone
     */
    showIdentityToEveryone?: boolean;
    /**
     * The review is shown to the author of the publication
     */
    showReviewToAuthor?: boolean;
    /**
     * The review is shown to everyone
     */
    showReviewToEveryone?: boolean;
    /**
     * Community option so that only invited users can create a review
     */
    privateReviews?: boolean;
}



