/**
 * Orvium API
 *  This is the OpenAPI 3.0 specification for the Orvium REST API.  Some useful links:  - [Orvium website](https://orvium.io) 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubscriptionType } from './subscriptionType';
import { CalendarDTO } from './calendarDTO';
import { CommunityType } from './communityType';
import { CommunityModeratorDTO } from './communityModeratorDTO';
import { FileExtensions } from './fileExtensions';
import { CommunityDTO } from './communityDTO';
import { AccessRight } from './accessRight';
import { CommunityStatus } from './communityStatus';
import { Track } from './track';


export interface CommunityPopulatedDTO { 
    status: CommunityStatus;
    type: CommunityType;
    subscription: SubscriptionType;
    customLicenses: Array<AccessRight>;
    preferredFileExtensions?: Array<FileExtensions>;
    /**
     * List of conferences associated with this community
     */
    conferenceProceedingsPopulated: Array<CommunityDTO>;
    /**
     * List of moderators of the community
     */
    moderatorsPopulated: Array<CommunityModeratorDTO>;
    /**
     * Community ID
     */
    _id: string;
    /**
     * Community name
     */
    name: string;
    /**
     * Community description
     */
    description?: string;
    /**
     * Community creator ID
     */
    creator: string;
    /**
     * the country of the community
     */
    country?: string;
    /**
     * Community codename
     */
    codename: string;
    /**
     * Community acknowledgement
     */
    acknowledgement?: string;
    /**
     * The twitter URL of the community
     */
    twitterURL?: string;
    /**
     * the facebook URL of the community
     */
    facebookURL?: string;
    /**
     * the website URL of the community
     */
    websiteURL?: string;
    /**
     * the logo URL of the community
     */
    logoURL?: string;
    /**
     * the banner URL of the community
     */
    bannerURL?: string;
    /**
     * the card image URL of the community
     */
    cardImageUrl?: string;
    /**
     * the guideline URL of the community
     */
    guidelinesURL?: string;
    /**
     * Community actions
     */
    actions: Array<string>;
    /**
     * Conferences ID associated with this community
     */
    conferenceProceedings: Array<string>;
    /**
     * New community tracks
     */
    newTracks: Array<Track>;
    /**
     * Community have privates reviewers
     */
    privateReviews: boolean;
    /**
     * Community option to give permission to authors to invite reviewers
     */
    canAuthorInviteReviewers: boolean;
    /**
     * Community issn
     */
    issn?: string;
    /**
     * Community calendar dates
     */
    calendarDates: Array<CalendarDTO>;
    /**
     * Community calendar visible
     */
    calendarVisible: boolean;
    /**
     * Community follower counts
     */
    followersCount: number;
    /**
     * Community products visible
     */
    productsVisible: boolean;
    /**
     * Community views
     */
    views: number;
    /**
     * The identity of the reviewer is shown to the author of the publication
     */
    showIdentityToAuthor: boolean;
    /**
     * The identity of the reviewer is shown to everyone
     */
    showIdentityToEveryone: boolean;
    /**
     * The review is shown to the author of the publication
     */
    showReviewToAuthor: boolean;
    /**
     * The review is shown to everyone
     */
    showReviewToEveryone: boolean;
}



