/**
 * Orvium API
 *  This is the OpenAPI 3.0 specification for the Orvium REST API.  Some useful links:  - [Orvium website](https://orvium.io) 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CalendarDTO } from './calendarDTO';
import { CommunityModeratorDTO } from './communityModeratorDTO';
import { CommunityStatus } from './communityStatus';
import { SubscriptionType } from './subscriptionType';
import { CommunityType } from './communityType';
import { CommunityPrivateDTO } from './communityPrivateDTO';
import { StripeDTO } from './stripeDTO';
import { CommunityPopulatedDTO } from './communityPopulatedDTO';
import { FileExtensions } from './fileExtensions';
import { CommunityDTO } from './communityDTO';
import { DataCiteDTO } from './dataCiteDTO';
import { CrossrefDTO } from './crossrefDTO';
import { AccessRight } from './accessRight';
import { Track } from './track';


/**
 * @type CommunitiesControllerGetCommunity200Response
 * @export
 */
export type CommunitiesControllerGetCommunity200Response = CommunityPopulatedDTO | CommunityPrivateDTO;

