/**
 * Orvium API
 *  This is the OpenAPI 3.0 specification for the Orvium REST API.  Some useful links:  - [Orvium website](https://orvium.io) 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateCommentDTO { 
    /**
     * Place where the comment was created
     */
    resourceModel: CreateCommentDTOResourceModelEnum;
    /**
     * Message of the comment
     */
    content: string;
    resource: string;
    /**
     * Comment id of the previous comment of the conversation
     */
    parent?: string;
}
export enum CreateCommentDTOResourceModelEnum {
    Deposit = 'Deposit',
    Review = 'Review'
};



