/**
 * Orvium API
 *  This is the OpenAPI 3.0 specification for the Orvium REST API.  Some useful links:  - [Orvium website](https://orvium.io) 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Author credit in the publicatuon
 */
export enum CreditType {
    Methodology = 'methodology',
    Conceptualization = 'conceptualization',
    Software = 'software',
    Validation = 'validation',
    FormalAnalysis = 'formal analysis',
    Investigation = 'investigation',
    Resources = 'resources',
    DataCuration = 'data curation',
    WritingOriginalDraft = 'writing original draft',
    WritingReviewAndEditing = 'writing review and editing',
    Visualization = 'visualization',
    Supervision = 'supervision',
    ProjectAdministration = 'project administration',
    FundingAcquisition = 'funding acquisition'
}

