/**
 * Orvium API
 *  This is the OpenAPI 3.0 specification for the Orvium REST API.  Some useful links:  - [Orvium website](https://orvium.io) 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CrossrefDTO { 
    /**
     * Prefix of the DOI
     */
    prefixDOI: string;
    /**
     * User id
     */
    user: string;
    /**
     * Crossref password
     */
    pass: string;
    /**
     * Crossref role
     */
    role: string;
    /**
     * Crossref server
     */
    server: CrossrefDTOServerEnum;
}
export enum CrossrefDTOServerEnum {
    TestCrossrefOrgServletDeposit = 'https://test.crossref.org/servlet/deposit',
    DoiCrossrefOrgServletDeposit = 'https://doi.crossref.org/servlet/deposit'
};



