/**
 * Orvium API
 *  This is the OpenAPI 3.0 specification for the Orvium REST API.  Some useful links:  - [Orvium website](https://orvium.io) 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DataCiteDTO { 
    /**
     * Prefix of the DOI
     */
    prefix: string;
    /**
     * Account id
     */
    accountId: string;
    /**
     * DataCite password
     */
    pass: string;
    /**
     * DataCite server
     */
    server: DataCiteDTOServerEnum;
}
export enum DataCiteDTOServerEnum {
    TestDataciteOrg = 'https://api.test.datacite.org',
    DataciteOrg = 'https://api.datacite.org'
};



