/**
 * Orvium API
 *  This is the OpenAPI 3.0 specification for the Orvium REST API.  Some useful links:  - [Orvium website](https://orvium.io) 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DoiLogDTO { 
    /**
     * Doi
     */
    doi: string;
    /**
     * Status of the doi
     */
    status: DoiLogDTOStatusEnum;
    /**
     * Data related to the submission of the doi, can be an error or success message
     */
    data?: string;
}
export enum DoiLogDTOStatusEnum {
    Processing = 'processing',
    Published = 'published',
    Failed = 'failed'
};



