/**
 * Orvium API
 *  This is the OpenAPI 3.0 specification for the Orvium REST API.  Some useful links:  - [Orvium website](https://orvium.io) 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EmailUsersDTO { 
    /**
     * User name
     */
    firstName: string;
    /**
     * User lastname
     */
    lastName: string;
    /**
     * User email
     */
    email: string;
    /**
     * User avatar
     */
    avatar?: string;
    /**
     * User gravatar
     */
    gravatar: string;
    /**
     * An array of actions
     */
    actions?: Array<string>;
}

