/**
 * Orvium API
 *  This is the OpenAPI 3.0 specification for the Orvium REST API.  Some useful links:  - [Orvium website](https://orvium.io) 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExtraMetadata { 
    /**
     * Conference title
     */
    conferenceTitle?: string | null;
    /**
     * The theme is the slogan or special emphasis of a conference in a particular year. It differs from the subject of a conference in that the subject is stable over the years while the theme may vary from year to year. For example, the American Society for Information Science and Technology conference theme was \"Knowledge: Creation, Organization and Use\" in 1999 and \"Defining Information Architecture\" in 2000.
     */
    conferenceTheme?: string | null;
    /**
     * Publication issn
     */
    issn?: string | null;
    /**
     * Publication isbn
     */
    isbn?: string | null;
    /**
     * Publication volume
     */
    volume?: number | null;
    /**
     * Publication issue
     */
    issue?: number | null;
    /**
     * Publication firstpage
     */
    firstpage?: number | null;
    /**
     * Publication lastpage
     */
    lastpage?: number | null;
    /**
     * Publication publisher name
     */
    publisher?: string | null;
    /**
     * The title of the journal of the publication
     */
    journalTitle?: string | null;
    /**
     * The dissertationName of the publication
     */
    dissertationName?: string | null;
    /**
     * The title of the inbook refered in the publication
     */
    inbookTitle?: string | null;
    /**
     * Language of the publication
     */
    language?: string | null;
    /**
     * Institution where the publications have been submitted
     */
    dissertationInstitution?: string | null;
    /**
     * Institution where the technical report have been done for the publication
     */
    technicalReportInstitution?: string | null;
    /**
     * The canonical URL is the URL of the best representative page from a group of duplicate pages
     */
    canonical?: string | null;
}

