/**
 * Orvium API
 *  This is the OpenAPI 3.0 specification for the Orvium REST API.  Some useful links:  - [Orvium website](https://orvium.io) 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FileMetadata { 
    /**
     * Name of the file
     */
    filename: string;
    /**
     * Description of the file
     */
    description: string;
    /**
     * File type
     */
    contentType: string;
    /**
     * Size of the file
     */
    contentLength: number;
    /**
     * Mark for what type of content the file is related
     */
    tags: Array<string>;
    /**
     * URL where the image is hosted \"   *
     */
    url?: string;
}

