/**
 * Orvium API
 *  This is the OpenAPI 3.0 specification for the Orvium REST API.  Some useful links:  - [Orvium website](https://orvium.io) 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InvitePopulatedDTO } from './invitePopulatedDTO';


export interface InviteQueryDTO { 
    /**
     * An array of invitations received by the query
     */
    invites: Array<InvitePopulatedDTO>;
    /**
     * Number of invitations received by the query
     */
    count: number;
    /**
     * An array of actions
     */
    actions?: Array<string>;
}

