/**
 * Orvium API
 *  This is the OpenAPI 3.0 specification for the Orvium REST API.  Some useful links:  - [Orvium website](https://orvium.io) 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MessageDTO { 
    /**
     * Message ID
     */
    _id: string;
    /**
     * The user that send the message
     */
    sender: string;
    /**
     * Date of the message
     */
    createdAt: Date;
    /**
     * Message content
     */
    content: string;
    /**
     * Conversation id
     */
    conversation: string;
    /**
     * Date of marked as read
     */
    readAt?: Date;
}

