/**
 * Orvium API
 *  This is the OpenAPI 3.0 specification for the Orvium REST API.  Some useful links:  - [Orvium website](https://orvium.io) 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderProductsDTO } from './orderProductsDTO';


export interface OrderDTO { 
    /**
     * The ID of the community where the order has been made
     */
    communityId: string;
    /**
     * An array of ordered products
     */
    products: Array<OrderProductsDTO>;
}

