/**
 * Orvium API
 *  This is the OpenAPI 3.0 specification for the Orvium REST API.  Some useful links:  - [Orvium website](https://orvium.io) 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Publication Type
 */
export enum PublicationType {
    Book = 'book',
    BookSection = 'book section',
    ConferencePaper = 'conference paper',
    Article = 'article',
    Patent = 'patent',
    Poster = 'poster',
    Preprint = 'preprint',
    Report = 'report',
    Dataset = 'dataset',
    SoftwareDocumentation = 'software documentation',
    Thesis = 'thesis',
    TechnicalNote = 'technical note',
    WorkingPaper = 'working paper',
    PolicyReport = 'policy report',
    RegisteredReport = 'registered report',
    Proposal = 'proposal',
    ReviewArticle = 'review article',
    Video = 'video',
    Abstract = 'abstract',
    ExtendedAbstract = 'extended abstract',
    Other = 'other'
}

