/**
 * Orvium API
 *  This is the OpenAPI 3.0 specification for the Orvium REST API.  Some useful links:  - [Orvium website](https://orvium.io) 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Keys } from './keys';


export interface PushSubscriptionDTO { 
    /**
     * The name of the endpoint is activating the notification
     */
    endpoint: string;
    /**
     * Expiration date of the subscription
     */
    expirationTime?: Date;
    /**
     * User ID
     */
    userId?: string;
    /**
     * A string with the encryption method used to generate a client key p256d: public key on the P-256 curve (that is, the NIST secp256r1 elliptic curve) auth: An authentication secret - https://datatracker.ietf.org/doc/html/draft-ietf-webpush-encryption-08
     */
    keys: Keys;
}

