/**
 * Orvium API
 *  This is the OpenAPI 3.0 specification for the Orvium REST API.  Some useful links:  - [Orvium website](https://orvium.io) 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReviewDecision } from './reviewDecision';
import { UserSummaryDTO } from './userSummaryDTO';
import { ReviewKind } from './reviewKind';
import { ReviewStatus } from './reviewStatus';


export interface ReviewSummaryDTO { 
    status: ReviewStatus;
    kind: ReviewKind;
    decision?: ReviewDecision;
    /**
     * Review ID
     */
    _id: string;
    /**
     * Review creator ID
     */
    creator: string;
    ownerProfile: UserSummaryDTO;
    /**
     * DOI of the review
     */
    doi?: string;
    /**
     * Review gravatar
     */
    gravatar?: string;
    /**
     * The url of the image put in the profile avatar
     */
    avatar?: string;
    /**
     * was invited for a review
     */
    wasInvited?: boolean;
    /**
     * The identity of the reviewer is shown to the author of the publication
     */
    showIdentityToAuthor: boolean;
    /**
     * The identity of the reviewer is shown to the everyone
     */
    showIdentityToEveryone: boolean;
}



