/**
 * Orvium API
 *  This is the OpenAPI 3.0 specification for the Orvium REST API.  Some useful links:  - [Orvium website](https://orvium.io) 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SpeakerDTO } from './speakerDTO';


export interface SessionDTO { 
    /**
     * Session ID
     */
    _id: string;
    /**
     * Session Title
     */
    title: string;
    /**
     * Session creator ID
     */
    creator: string;
    /**
     * The track timpestamp of the session
     */
    newTrackTimestamp?: number;
    /**
     * The description of the session
     */
    description?: string;
    /**
     * The ID of the community where the session is created
     */
    community: string;
    /**
     * Session start date
     */
    dateStart?: Date;
    /**
     * Speakers of the current session
     */
    speakers: Array<SpeakerDTO>;
    /**
     * Session end date
     */
    dateEnd?: Date;
    /**
     * Publications ID related to the session
     */
    deposits: Array<string>;
    /**
     * Session actions
     */
    actions: Array<string>;
}

