/**
 * Orvium API
 *  This is the OpenAPI 3.0 specification for the Orvium REST API.  Some useful links:  - [Orvium website](https://orvium.io) 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimilarityMetadataAllOfTopMatches } from './similarityMetadataAllOfTopMatches';


export interface SimilarityMetadata { 
    overall_match_percentage: number;
    internet_match_percentage?: number | null;
    publication_match_percentage?: number | null;
    submitted_works_match_percentage?: number | null;
    submission_id: string;
    status: string;
    time_generated: string;
    time_requested: string;
    top_matches: Array<SimilarityMetadataAllOfTopMatches>;
    top_source_largest_matched_word_count: number;
}

