/**
 * Orvium API
 *  This is the OpenAPI 3.0 specification for the Orvium REST API.  Some useful links:  - [Orvium website](https://orvium.io) 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StripeLineItem { 
    /**
     * Unique identifier for the object Stripe LineItem. LineItem is A list of items the customer is being quoted for.
     */
    id: string;
    /**
     * String representing the objects type.
     */
    object: string;
    /**
     * Total discount amount applied. If no discounts were applied, defaults to 0.
     */
    amount_discount: number;
    /**
     * Total before any discounts or taxes are applied.
     */
    amount_subtotal: number;
    /**
     * Total tax amount applied. If no tax was applied, defaults to 0.
     */
    amount_tax: number;
    /**
     * Total after discounts and taxes.
     */
    amount_total: number;
    /**
     * It is the currency in which payments can be made in that community. Must be a supported currency.
     */
    currency: string;
    /**
     * A string attached to the object. Often useful for displaying to users. Defaults to product name.
     */
    description: string;
    /**
     * The discounts applied to the line item. This field is not included by default. To include it in the response, expand the discounts field.
     */
    discounts: Array<string>;
    /**
     * The price used to generate the line item.
     */
    price: object;
    /**
     * Products describe the specific goods or services you offer to your customers.
     */
    product: object;
    /**
     * The quantity of products being purchased.
     */
    quantity: object;
    /**
     * The taxes applied to the line item. This field is not included by default.
     */
    taxes: Array<string>;
}

