/**
 * Orvium API
 *  This is the OpenAPI 3.0 specification for the Orvium REST API.  Some useful links:  - [Orvium website](https://orvium.io) 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StripeProductDTODefaultPrice } from './stripeProductDTODefaultPrice';


export interface StripeProductDTO { 
    /**
     * Unique identifier for the object Product. Products describe the specific goods or services you offer to your customers.
     */
    id: string;
    /**
     * String representing the objects type.
     */
    object: string;
    /**
     * Whether the product is currently available for purchase.
     */
    active?: boolean;
    /**
     * The product attributes
     */
    attributes?: Array<string> | null;
    /**
     * The product caption
     */
    caption?: string | null;
    /**
     * Time at which the object was created. Measured in seconds since the Unix epoch.
     */
    created?: number;
    default_price?: StripeProductDTODefaultPrice | null;
    /**
     * The product’s description, meant to be displayable to the customer. Use this field to optionally store a long form explanation of the product being sold for your own rendering purposes.
     */
    description?: string | null;
    /**
     * A list of up to 8 URLs of images for this product, meant to be displayable to the customer.
     */
    images?: Array<string>;
    /**
     * Has the value true if the object exists in live mode or the value false if the object exists in test mode.
     */
    livemode?: boolean;
    /**
     * Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
     */
    metadata?: object;
    /**
     * The product’s name, meant to be displayable to the customer.
     */
    name?: string;
    /**
     * The dimensions of this product for shipping purposes.
     */
    package_dimensions?: object | null;
    /**
     * Whether this product is shipped (i.e., physical goods).
     */
    shippable?: boolean | null;
    /**
     * Extra information about a product which will appear on your customer’s credit card statement. In the case that multiple products are billed at once, the first statement descriptor will be used.
     */
    statement_descriptor?: string | null;
    /**
     * Whether the product was a good or service.
     */
    type?: string;
    /**
     * A label that represents units of this product. When set, this will be included in customers’ receipts, invoices, Checkout, and the customer portal.
     */
    unit_label?: string | null;
    /**
     * Time at which the object was last updated. Measured in seconds since the Unix epoch.
     */
    updated?: number;
    /**
     * A URL of a publicly-accessible webpage for this product.
     */
    url?: string | null;
    actions: Array<string>;
}

