/**
 * Orvium API
 *  This is the OpenAPI 3.0 specification for the Orvium REST API.  Some useful links:  - [Orvium website](https://orvium.io) 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StripePrice { 
    /**
     * Unique identifier for the object Price. Prices define the unit cost, currency, and (optional) billing cycle for both recurring and one-time purchases of products.
     */
    id: string;
    /**
     * String representing the objects type.
     */
    object: string;
    /**
     * Whether the price can be used for new purchases.
     */
    active?: boolean;
    /**
     * Describes how to compute the price per period. Either per_unit or tiered.
     */
    billing_scheme?: string;
    /**
     * Time at which the object was created. Measured in seconds since the Unix epoch.
     */
    created?: number;
    /**
     * It is the currency in which payments can be made in that community. Must be a supported currency.
     */
    currency: string;
    /**
     * When set, provides configuration for the amount to be adjusted by the customer during Checkout Sessions and Payment Links.
     */
    custom_unit_amount?: object | null;
    /**
     * Has the value true if the object exists in live mode or the value false if the object exists in test mode.
     */
    livemode?: boolean;
    /**
     * Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format. 
     */
    metadata?: object;
    /**
     * A brief description of the price, hidden from customers.
     */
    nickname?: string | null;
    /**
     * The recurring components of a price such as interval and usage_type.
     */
    recurring?: object | null;
    /**
     * Specifies whether the price is considered inclusive of taxes or exclusive of taxes. One of inclusive, exclusive, or unspecified. Once specified as either inclusive or exclusive, it cannot be changed.
     */
    tax_behavior?: string | null;
    /**
     * One of one_time or recurring depending on whether the price is for a one-time purchase or a recurring (subscription) purchase.
     */
    type?: string;
    /**
     * A positive integer in cents (or 0 for a free price) representing how much to charge. One of unit_amount or custom_unit_amount is required, unless billing_scheme=tiered.
     */
    unit_amount: number;
    /**
     * Same as unit_amount, but accepts a decimal value in cents with at most 12 decimal places. Only one of unit_amount and unit_amount_decimal can be set.
     */
    unit_amount_decimal: string;
}

