/**
 * Orvium API
 *  This is the OpenAPI 3.0 specification for the Orvium REST API.  Some useful links:  - [Orvium website](https://orvium.io) 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum SubmissionErrorCodeEnum {
    UnsupportedFiletype = 'UNSUPPORTED_FILETYPE',
    ProcessingError = 'PROCESSING_ERROR',
    CannotExtractText = 'CANNOT_EXTRACT_TEXT',
    TooLittleText = 'TOO_LITTLE_TEXT',
    TooMuchText = 'TOO_MUCH_TEXT',
    TooManyPages = 'TOO_MANY_PAGES',
    FileLocked = 'FILE_LOCKED',
    CorruptFile = 'CORRUPT_FILE'
}

