/**
 * Orvium API
 *  This is the OpenAPI 3.0 specification for the Orvium REST API.  Some useful links:  - [Orvium website](https://orvium.io) 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Mark if the email template is a system or a customizable email
 */
export enum TemplateCategory {
    System = 'system',
    Moderator = 'moderator',
    Community = 'community',
    Publication = 'publication',
    Review = 'review',
    ReviewInvitation = 'review-invitation',
    Editor = 'editor'
}

