/**
 * Orvium API
 *  This is the OpenAPI 3.0 specification for the Orvium REST API.  Some useful links:  - [Orvium website](https://orvium.io) 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthorUpdateDTO } from './authorUpdateDTO';
import { Reference } from './reference';
import { PublicationType } from './publicationType';
import { DepositStatus } from './depositStatus';
import { AccessRight } from './accessRight';
import { BibtexReferences } from './bibtexReferences';
import { ExtraMetadata } from './extraMetadata';
import { ReviewType } from './reviewType';


export interface UpdateDepositDTO { 
    publicationType?: PublicationType;
    accessRight?: AccessRight;
    status?: DepositStatus;
    reviewType?: ReviewType;
    /**
     * List of blockchain transaction associated with this publication
     */
    transactions?: { [key: string]: any; };
    /**
     * Publication title
     */
    title?: string;
    /**
     * Publication abstract
     */
    abstract?: string;
    /**
     * Editor ID assigned to the publication
     */
    assignee?: string;
    /**
     * Publication date
     */
    publicationDate?: Date;
    /**
     * Submission date
     */
    submissionDate?: Date;
    /**
     * List of authors of the publication
     */
    authors?: Array<AuthorUpdateDTO>;
    /**
     * Keccak256 hash of the main publication file. Keccak256 is a cryptographic function built into solidity. Can be used for cryptographic signature with a small size.
     */
    keccak256?: string;
    /**
     * List of keywords for the publication
     */
    keywords?: Array<string>;
    /**
     * DOI of the publication
     */
    doi?: string;
    /**
     * List of disciplines associated to the publication
     */
    disciplines?: Array<string>;
    /**
     * List of references of the publication
     */
    references?: Array<Reference>;
    /**
     * List of bibtex references of the publication
     */
    bibtexReferences?: Array<BibtexReferences>;
    /**
     * The track timestamp of the publication
     */
    newTrackTimestamp?: number;
    /**
     * This flag enables the creation of peer reviews for this publication
     */
    canBeReviewed?: boolean;
    /**
     * Deposit internal option to give permission to authors to invite reviewers
     */
    canAuthorInviteReviewers?: boolean;
    /**
     * The url of the associated git repository
     */
    gitRepository?: string;
    /**
     * Extra information required by journals and conferences
     */
    extraMetadata?: ExtraMetadata;
    /**
     * Html extracted automatically for the main publication file
     */
    html?: string;
}



