/**
 * Orvium API
 *  This is the OpenAPI 3.0 specification for the Orvium REST API.  Some useful links:  - [Orvium website](https://orvium.io) 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReviewDecision } from './reviewDecision';


export interface UpdateReviewDTO { 
    decision?: ReviewDecision;
    /**
     * Review transactions
     */
    transactions?: { [key: string]: any; };
    /**
     * Review  author
     */
    author?: string;
    /**
     * Review comments
     */
    comments?: string;
    /**
     * Review reward
     */
    reward?: number;
    /**
     * DOI of the review
     */
    doi?: string;
    /**
     * Review publication date
     */
    publicationDate?: Date;
    /**
     * was invited for a review
     */
    wasInvited?: boolean;
    /**
     * Html extracted automatically for the main review file
     */
    html?: string;
    /**
     * Keccak256 is a cryptographic function built into solidity. Can be used for cryptographic signature with a small size.
     */
    keccak256?: string;
    /**
     * Reason to accept a review
     */
    reason?: string;
    /**
     * The review is shown to the author of the publication
     */
    showReviewToAuthor?: boolean;
    /**
     * The review is shown to everyone
     */
    showReviewToEveryone?: boolean;
    /**
     * The identity of the reviewer is shown to the author of the publication
     */
    showIdentityToAuthor?: boolean;
    /**
     * The identity of the reviewer is shown to everyone
     */
    showIdentityToEveryone?: boolean;
}



