/**
 * Orvium API
 *  This is the OpenAPI 3.0 specification for the Orvium REST API.  Some useful links:  - [Orvium website](https://orvium.io) 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserType } from './userType';


export interface UpdateUserDTO { 
    userType?: UserType;
    /**
     * User email
     */
    emailPendingConfirmation?: string;
    /**
     * User fist name
     */
    firstName?: string;
    /**
     * User last name
     */
    lastName?: string;
    /**
     * User description
     */
    aboutMe?: string;
    /**
     * User orcid
     */
    orcid?: string;
    /**
     * User linkedin url
     */
    linkedin?: string;
    /**
     * Blog url
     */
    blog?: string;
    /**
     * Institutions of the user
     */
    institutions?: Array<string>;
    /**
     * User role in the platform
     */
    role?: string;
    /**
     * Publications where the user is mentioned as author or submitter in the platform
     */
    starredDeposits?: Array<string>;
    /**
     * Check if the user has finished the sign-up
     */
    isOnboarded?: boolean;
    /**
     * Check if the user has accepted the Terms and Conditions
     */
    acceptedTC?: boolean;
    /**
     * Communities that have joined the user
     */
    communities?: Array<string>;
    /**
     * User disciplines
     */
    disciplines?: Array<string>;
    /**
     * Check if the user is impersonating another user
     */
    impersonatedUser?: string;
}



