/**
 * Orvium API
 *  This is the OpenAPI 3.0 specification for the Orvium REST API.  Some useful links:  - [Orvium website](https://orvium.io) 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VideoDTO { 
    /**
     * Video name
     */
    name: string;
    /**
     * The url where the video is hosted
     */
    videoUrl: string;
    /**
     * The type of the video file
     */
    videoType: string;
    /**
     * Action that can be made in the video
     */
    actions: Array<string>;
}

