# Dockerfile para api
# Usa una imagen de Node.js 20 como base
FROM node:20

# Establece el directorio de trabajo
WORKDIR /app

# Copia el package.json y package-lock.json
COPY ../../package*.json ./

# Instala las dependencias
RUN npm ci

# Copia el resto de los archivos de la aplicación
COPY . .

RUN npx nx run api:build:production && ls -la ./dist/apps/api

RUN ls -la



# Expone el puerto 3000
EXPOSE 3000

# Comando para ejecutar la aplicación
CMD ["node", "dist/apps/api/main.js"]
