# Dockerfile para api
# Usa una imagen de Node.js 20 como base
FROM node:20

# Establece el directorio de trabajo
WORKDIR /app

# Copia el package.json y package-lock.json desde el directorio raíz del monorepo
COPY ../../package*.json ./

# Instala todas las dependencias
RUN npm install

# Copia los archivos compilados de la API
COPY ./dist/apps/api ./

# Expone el puerto 3000
EXPOSE 3000

# Comando para ejecutar la aplicación
CMD ["node", "main.js"]
