FROM orvium-agent-base:latest
USER root

# Directorio de trabajo
WORKDIR /home/nestuser/app


# Copia solo package.json y package-lock.json
COPY package*.json ./

RUN chown -R nestuser:nestuser . 

USER nestuser

# Instala dependencias (como usuario nestuser)
RUN npm install

# Copia el resto del código
COPY . .

USER root

# Construye la app
RUN npx nx reset && npx nx run api:build:agent --configuration=production

# Entrypoint
ENTRYPOINT ["node", "dist/apps/api-agent/main.js"]